name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["go1.19", "jsc11", "minimal", "node18", "perl5.36", "php8.1", "python3.11", "ruby3.1"]
    steps:
    - uses: actions/checkout@v2

    - name: build dockerfiles
      run: |
        make dockerfiles

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.${{ matrix.image }}
        push: true
        tags: mmicael/nginx-unit:master-${{ matrix.image }}
